In [1]:
# LTC_1_notebook/notebooks/OpenerAndParserExel.ipynb
# importing some libraries
import pandas as pd

In [2]:
def OpenerCouneterRows(path):
    """
    path: str Путь до файла .xlsx
    rerurn: data_exel DataFrame
            ncols list 
    
    Функция возвращает нам DataFrame в виде 
    исходного DataFrame с конкретными номерами
    столбцов, т.к. у исходного их нет
    """
    data_excel_head = pd.read_excel(path, nrows=50)
    ncols_data = data_excel_head.shape[1]
    ncols = []
    for col in range(ncols_data):
        ncols.append('Col{}'.format(col))

    data_excel = pd.read_excel(path, names=ncols)
    
    return data_excel, ncols

In [3]:
path = '/home/sergey/PycharmProjects/LTC_1_notebook/exel_data/Chapter_1_buildibgs.xlsx'

data_excel, ncols = OpenerCouneterRows(path)

In [4]:
def searcher_row(data):
    """
    data: dataframe
    return: num_row (int)
    
    Функция ищет строчку, в которой находится №пп для того,
    чтобы потом взять эту строчку и вытянуть из нее необходимую
    шапку для будующей таблицы
    """
    for row, column in data[0:10].iterrows():
        for i in range(len(column)):
            # print(row, column[i])
            if '№пп' in str(column[i]):
                num_row = row
    return num_row

In [5]:
num_row = searcher_row(data_excel[:100])

In [33]:
def target_columns(data, num_row):
    string = data.loc[num_row].dropna().to_list()
                
    return string

def target_columns_list(string):
    target_string = []
    for item in string:
        if item in ['№пп', 'Шифр, номера нормативов и коды ресурсов',
                        'Наименование работ и затрат','Ед. изм.', 'Кол-во единиц']:
            target_string.append(item)
            
    return target_string

In [34]:
string = target_columns(data=data_excel, num_row=num_row)
target_string = target_columns_list(string)

In [32]:
string

['№пп',
 'Шифр, номера нормативов и коды ресурсов',
 'Наименование работ и затрат',
 'Ед. изм.',
 'Кол-во единиц',
 'Цена на единицу измерения, руб.',
 'Поправочные коэффициенты',
 'Коэффициенты зимних удорожаний',
 'Коэффициенты пересчета',
 'ВСЕГО затрат, руб.',
 'Справ.']

In [35]:
target_string

['№пп',
 'Шифр, номера нормативов и коды ресурсов',
 'Наименование работ и затрат',
 'Ед. изм.',
 'Кол-во единиц']

In [7]:
data_excel[4:14]

,Col0,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,...,Col11,Col12,Col13,Col14,Col15,Col16,Col17,Col18,Col19,Col20
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Сметная стоимость,NaN,NaN,NaN,NaN,2240845.636,NaN,NaN,тыс.руб.
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Средства на оплату труда,NaN,NaN,NaN,NaN,700949.489,NaN,тыс.руб.
6,Составлен(а) в уровне текущих (прогнозных) цен...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,№пп,NaN,"Шифр, номера нормативов и коды ресурсов",NaN,Наименование работ и затрат,NaN,Ед. изм.,Кол-во единиц,"Цена на единицу измерения, руб.",NaN,...,Поправочные коэффициенты,NaN,NaN,Коэффициенты зимних удорожаний,Коэффициенты пересчета,"ВСЕГО затрат, руб.",NaN,NaN,Справ.,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ЗТР, всего чел-ч",NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Стоим. ед. с нач., руб.",NaN
10,1,NaN,2,NaN,3,NaN,4,5,6,NaN,...,7,NaN,NaN,8,9,10,NaN,NaN,11,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Раздел 1.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN